{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a96cbe9c",
   "metadata": {},
   "outputs": [],
   "source": [
    "def function_index(Time, topo_i, topo_o):\n",
    "    \n",
    "    #-------------------------------------------------------------------------------------------------------------              \n",
    "    #\n",
    "    # \n",
    "    topo_x = {}\n",
    "    Tanks_ = list(set(list(topo_i.keys()) + list(topo_o.keys())))\n",
    "    for tank in Tanks_:\n",
    "        prods = []\n",
    "        if tank in topo_i:\n",
    "            for line in topo_i[tank]:\n",
    "                for prod in topo_i[tank][line]:\n",
    "                    prods.append(prod)\n",
    "        if tank in topo_o:\n",
    "            for line in topo_o[tank]:\n",
    "                for prod in topo_o[tank][line]:\n",
    "                    prods.append(prod)\n",
    "        prods = set(prods)        \n",
    "        for prod in prods:\n",
    "            topo_x[tank] = {prod:0}\n",
    "\n",
    "    #-------------------------------------------------------------------------------------------------------------              \n",
    "    #\n",
    "    #   \n",
    "    i_index = []\n",
    "    for tank in topo_i:\n",
    "        for line in topo_i[tank]:\n",
    "            for product in topo_i[tank][line]:\n",
    "                for time in Time:\n",
    "                    i_index.append((tank, line, product, time))\n",
    "\n",
    "    #-------------------------------------------------------------------------------------------------------------              \n",
    "    #\n",
    "    #    \n",
    "    o_index = []\n",
    "    for tank in topo_o:\n",
    "        for line in topo_o[tank]:\n",
    "            for product in topo_o[tank][line]:\n",
    "                for time in Time:\n",
    "                    o_index.append((tank, line, product, time))  \n",
    "\n",
    "    #-------------------------------------------------------------------------------------------------------------              \n",
    "    #\n",
    "    #            \n",
    "    x_index = []\n",
    "    for tank in topo_x:\n",
    "        for prod in topo_x[tank]:\n",
    "            for time in Time:\n",
    "                x_index.append((tank, prod, time))            \n",
    "\n",
    "    #-------------------------------------------------------------------------------------------------------------              \n",
    "    #\n",
    "    #            \n",
    "    mi_index = [] \n",
    "    tups = set([tup[1:3] for tup in i_index if tup[3] == 0])\n",
    "    for tup in tups:\n",
    "        for time in Time:\n",
    "            mi_index.append(tup + (time,))\n",
    "\n",
    "    mo_index = [] \n",
    "    tups = set([tup[1:3] for tup in o_index if tup[3] == 0])\n",
    "    for tup in tups:\n",
    "        for time in Time:\n",
    "            mo_index.append(tup + (time,))    \n",
    "\n",
    "    #-------------------------------------------------------------------------------------------------------------              \n",
    "    #\n",
    "    #              \n",
    "    li_index = []\n",
    "    lst = set([tup[1:4] for tup in i_index])\n",
    "    for tup in lst:\n",
    "        li_index.append(tup)   \n",
    "\n",
    "    lo_index = []\n",
    "    lst = set([tup[1:4] for tup in o_index])\n",
    "    for tup in lst:\n",
    "        lo_index.append(tup) \n",
    "\n",
    "    #-------------------------------------------------------------------------------------------------------------              \n",
    "    #\n",
    "    #              \n",
    "    ti_index = []\n",
    "    lst = set([tup[0:4] for tup in i_index])\n",
    "    for tup in lst:\n",
    "        ti_index.append(tup) \n",
    "\n",
    "    to_index = []\n",
    "    lst = set([tup[0:4] for tup in o_index])\n",
    "    for tup in lst:\n",
    "        to_index.append(tup) \n",
    "\n",
    "    #-------------------------------------------------------------------------------------------------------------              \n",
    "    #\n",
    "    #              \n",
    "    tlpo_index = []\n",
    "    lst = set([tup[0:3] for tup in o_index])\n",
    "    for tup in lst:\n",
    "        tlpo_index.append(tup)\n",
    "        \n",
    "    #-------------------------------------------------------------------------------------------------------------              \n",
    "    #\n",
    "    #    \n",
    "    return (i_index)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
